### PR TITLE
Feature/person component about page 080116

### PR DESCRIPTION
**Pull request by sabor413**
Created the about people grid and tile components...  taking a shot of adding a component to go through the process of performing this with this one to ensure that I perform the process correctly.  Also the code is ready and the items have been synced with TDS, please let me know if this is OK or should  I wait for Unicorn.  Thanks :)

The ticket links below are the tasks I created in VSO to track this effort as well, please let me know if you have any questions.

https://perficient-msftnbu.visualstudio.com/Perficient%20-%20Sitecore/_workitems/edit/27156
https://perficient-msftnbu.visualstudio.com/Perficient%20-%20Sitecore/_workitems/edit/27157

### CODE REVIEW

**Comment by sabor413** [comment]
Today, I have included the needed items and demo content as Unicorn serialized yml files, so it should be ready for review.  I have added an About Page item in the content section containing the component I developed and demo content based on the original HTML file.

**Comment by sabor413** [comment]
Hold off on this feature branch, it does not reflect the latest Ignition code and Unicorn predicate structure.

**Comment by jonupchurch** [comment]
Should we close it till you reopen another PR?

**Comment by sabor413** [comment]
Yeah, that is fine, I was treating it more like a reminder, I am going to
close and submit the new one most likely before the day is over.

Thanks :)

**Comment by sabor413** [comment]
Closing this branch, will be resubmitting with the latest code base soon.

**Pull request closed without merging**
